name: lcoa-opt-env
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - numpy
  - pyomo
  - pypsa
  - gurobi
  - ca-certificates
  - certifi
  - openssl
  - geopandas
  - openpyxl
  - ipykernel
  - h5netcdf
  - geopy
  - plotly
  - nbformat
  - xlsxwriter
  - glpk
