name: lcoa-opt-env
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - numpy
  - pyomo=6.6.1
  - pypsa=0.25.1
  - linopy=0.2.4
  - glpk
  - ca-certificates
  - certifi
  - openssl
  - geopandas
  - openpyxl
  - ipykernel
  - h5netcdf
  - geopy
  - plotly
  - nbformat